language: node_js
sudo: false

node_js:
  - "9"

cache:
  yarn: true
  directories:
    - ".eslintcache"

install:
  - yarn install

script:
  - yarn eslint
  - yarn test

after_success:
   - yarn coverage
   - yarn coverage-report